# Form implementation generated from reading ui file '.\main_windowui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 623)
        MainWindow.setMinimumSize(QtCore.QSize(1011, 623))
        MainWindow.setMaximumSize(QtCore.QSize(1011, 623))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icon/yandexlogo.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(
            "QToolTip { \n"
            "    background-color: black; \n"
            "    color: white; \n"
            "    border: black solid 1px\n"
            "                          \n"
            "}\n"
            "#MainWindow QPushButton{\n"
            "    color: white;\n"
            "    border: none;\n"
            "\n"
            "}\n"
            "\n"
            "#MainWindow QPushButton:flat {\n"
            "     border: none;\n"
            " }\n"
            "\n"
            "#MainWindow QPushButton:pressed{\n"
            "    background-color: #fcca00;\n"
            "    border-bottom: 2px solid #fcca00;\n"
            "}\n"
            "#MainWindow QPushButton:checked{\n"
            "    background-color: #fcca00;\n"
            "    border-bottom: 2px solid #fcca00;\n"
            "\n"
            "}"
        )
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidebar = QtWidgets.QFrame(parent=self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 161, 551))
        self.sidebar.setStyleSheet("background-color: rgb(68, 68, 68);")
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logolayout = QtWidgets.QHBoxLayout()
        self.logolayout.setContentsMargins(0, 0, -1, -1)
        self.logolayout.setSpacing(0)
        self.logolayout.setObjectName("logolayout")
        self.logo = QtWidgets.QLabel(parent=self.sidebar)
        self.logo.setMaximumSize(QtCore.QSize(50, 50))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/icon/yandexlogo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.logolayout.addWidget(self.logo)
        self.verticalLayout_2.addLayout(self.logolayout)
        self.buttons_layout = QtWidgets.QVBoxLayout()
        self.buttons_layout.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint
        )
        self.buttons_layout.setContentsMargins(0, -1, -1, -1)
        self.buttons_layout.setSpacing(25)
        self.buttons_layout.setObjectName("buttons_layout")
        self.my_likes = QtWidgets.QPushButton(parent=self.sidebar)
        self.my_likes.setMinimumSize(QtCore.QSize(0, 50))
        self.my_likes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.my_likes.setBaseSize(QtCore.QSize(0, 0))
        self.my_likes.setStyleSheet('font: 13pt "Fira Sans";\n' "color: white;")
        self.my_likes.setFlat(False)
        self.my_likes.setObjectName("my_likes")
        self.buttons_layout.addWidget(self.my_likes)
        self.my_wave = QtWidgets.QPushButton(parent=self.sidebar)
        self.my_wave.setMinimumSize(QtCore.QSize(0, 50))
        self.my_wave.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.my_wave.setStyleSheet('font: 13pt "Fira Sans";\n' "color: white;")
        self.my_wave.setAutoDefault(False)
        self.my_wave.setFlat(False)
        self.my_wave.setObjectName("my_wave")
        self.buttons_layout.addWidget(self.my_wave)
        self.my_playlist = QtWidgets.QPushButton(parent=self.sidebar)
        self.my_playlist.setMinimumSize(QtCore.QSize(0, 50))
        self.my_playlist.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.my_playlist.setStyleSheet('font: 13pt "Fira Sans";\n' "color: white;")
        self.my_playlist.setFlat(False)
        self.my_playlist.setObjectName("my_playlist")
        self.buttons_layout.addWidget(self.my_playlist)
        self.my_albums = QtWidgets.QPushButton(parent=self.sidebar)
        self.my_albums.setMinimumSize(QtCore.QSize(0, 50))
        self.my_albums.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.my_albums.setStyleSheet('font: 13pt "Fira Sans";\n' "color: white;")
        self.my_albums.setFlat(False)
        self.my_albums.setObjectName("my_albums")
        self.buttons_layout.addWidget(self.my_albums)
        self.my_queue = QtWidgets.QPushButton(parent=self.sidebar)
        self.my_queue.setMinimumSize(QtCore.QSize(0, 50))
        self.my_queue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.my_queue.setStyleSheet('font: 13pt "Fira Sans";\n' "color: white;")
        self.my_queue.setFlat(False)
        self.my_queue.setObjectName("my_queue")
        self.buttons_layout.addWidget(self.my_queue)
        self.playlists_list = QtWidgets.QListWidget(parent=self.sidebar)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        self.playlists_list.setFont(font)
        self.playlists_list.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.playlists_list.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.playlists_list.setLineWidth(0)
        self.playlists_list.setProperty("showDropIndicator", True)
        self.playlists_list.setObjectName("playlists_list")
        self.buttons_layout.addWidget(self.playlists_list)
        self.verticalLayout_2.addLayout(self.buttons_layout)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 550, 1011, 51))
        self.frame_3.setStyleSheet("background-color: rgb(68, 68, 68);\n" "")
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.player_cover = QtWidgets.QLabel(parent=self.frame_3)
        self.player_cover.setMaximumSize(QtCore.QSize(50, 50))
        self.player_cover.setStyleSheet("border-radius: 15px;")
        self.player_cover.setText("")
        self.player_cover.setPixmap(QtGui.QPixmap(":/icon/music_cover.jpg"))
        self.player_cover.setScaledContents(True)
        self.player_cover.setWordWrap(False)
        self.player_cover.setObjectName("player_cover")
        self.horizontalLayout_3.addWidget(self.player_cover)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.track_title = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        self.track_title.setFont(font)
        self.track_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.track_title.setObjectName("track_title")
        self.verticalLayout_5.addWidget(self.track_title)
        self.track_author = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        self.track_author.setFont(font)
        self.track_author.setStyleSheet("color: white;")
        self.track_author.setText("")
        self.track_author.setObjectName("track_author")
        self.verticalLayout_5.addWidget(self.track_author)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.like_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.like_button.setMaximumSize(QtCore.QSize(50, 50))
        self.like_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/icon/heart.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.like_button.setIcon(icon1)
        self.like_button.setIconSize(QtCore.QSize(20, 20))
        self.like_button.setFlat(False)
        self.like_button.setObjectName("like_button")
        self.horizontalLayout_3.addWidget(self.like_button)
        self.current_time = QtWidgets.QLabel(parent=self.frame_3)
        self.current_time.setStyleSheet(
            "color: rgb(255, 255, 255);\n" 'font: 8pt "Fira Sans"; '
        )
        self.current_time.setLineWidth(0)
        self.current_time.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.current_time.setObjectName("current_time")
        self.horizontalLayout_3.addWidget(self.current_time)
        self.timeline = QtWidgets.QSlider(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeline.sizePolicy().hasHeightForWidth())
        self.timeline.setSizePolicy(sizePolicy)
        self.timeline.setStyleSheet(
            "QSlider::groove:horizontal {\n"
            "    height: 5px;\n"
            "    margin: 0px;\n"
            "    border-radius: 3px;\n"
            "    background: #B0AEB1;\n"
            "    background: rgb(255, 255, 255, 0.4);\n"
            "}\n"
            "\n"
            "QSlider::handle:horizontal {\n"
            "    background: #fff;\n"
            "    width: 5px;\n"
            "    margin: -3px 0;\n"
            "}\n"
            "\n"
            "QSlider::sub-page:qlineargradient {\n"
            "    background: #ffdb4d;\n"
            "    border-radius: 3px;\n"
            "}\n"
            ""
        )
        self.timeline.setProperty("value", 0)
        self.timeline.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.timeline.setObjectName("timeline")
        self.horizontalLayout_3.addWidget(self.timeline)
        self.wait_time = QtWidgets.QLabel(parent=self.frame_3)
        self.wait_time.setStyleSheet(
            "color: rgb(255, 255, 255);\n" 'font: 8pt "Fira Sans"; '
        )
        self.wait_time.setObjectName("wait_time")
        self.horizontalLayout_3.addWidget(self.wait_time)
        self.volume_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.volume_button.setMaximumSize(QtCore.QSize(30, 50))
        self.volume_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.volume_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/icon/volume.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.volume_button.setIcon(icon2)
        self.volume_button.setIconSize(QtCore.QSize(30, 30))
        self.volume_button.setCheckable(True)
        self.volume_button.setChecked(False)
        self.volume_button.setFlat(False)
        self.volume_button.setObjectName("volume_button")
        self.horizontalLayout_3.addWidget(self.volume_button)
        self.shuffle_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.shuffle_button.setMaximumSize(QtCore.QSize(50, 50))
        self.shuffle_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/icon/shuffle.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.shuffle_button.setIcon(icon3)
        self.shuffle_button.setIconSize(QtCore.QSize(30, 30))
        self.shuffle_button.setCheckable(True)
        self.shuffle_button.setChecked(False)
        self.shuffle_button.setFlat(False)
        self.shuffle_button.setObjectName("shuffle_button")
        self.horizontalLayout_3.addWidget(self.shuffle_button)
        self.previus_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.previus_button.setMaximumSize(QtCore.QSize(50, 50))
        self.previus_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/icon/back.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.previus_button.setIcon(icon4)
        self.previus_button.setIconSize(QtCore.QSize(30, 30))
        self.previus_button.setFlat(False)
        self.previus_button.setObjectName("previus_button")
        self.horizontalLayout_3.addWidget(self.previus_button)
        self.playpause_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.playpause_button.setMaximumSize(QtCore.QSize(50, 50))
        self.playpause_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/icon/play.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.playpause_button.setIcon(icon5)
        self.playpause_button.setIconSize(QtCore.QSize(30, 30))
        self.playpause_button.setAutoDefault(False)
        self.playpause_button.setDefault(True)
        self.playpause_button.setFlat(False)
        self.playpause_button.setObjectName("playpause_button")
        self.horizontalLayout_3.addWidget(self.playpause_button)
        self.forward_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.forward_button.setMaximumSize(QtCore.QSize(50, 50))
        self.forward_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/icon/skip.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.forward_button.setIcon(icon6)
        self.forward_button.setIconSize(QtCore.QSize(30, 30))
        self.forward_button.setFlat(False)
        self.forward_button.setObjectName("forward_button")
        self.horizontalLayout_3.addWidget(self.forward_button)
        self.repeat_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.repeat_button.setMaximumSize(QtCore.QSize(50, 50))
        self.repeat_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(":/icon/repeat.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.repeat_button.setIcon(icon7)
        self.repeat_button.setIconSize(QtCore.QSize(30, 30))
        self.repeat_button.setCheckable(True)
        self.repeat_button.setChecked(False)
        self.repeat_button.setFlat(False)
        self.repeat_button.setObjectName("repeat_button")
        self.horizontalLayout_3.addWidget(self.repeat_button)
        self.Content = QtWidgets.QFrame(parent=self.centralwidget)
        self.Content.setGeometry(QtCore.QRect(160, 0, 851, 551))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Content.sizePolicy().hasHeightForWidth())
        self.Content.setSizePolicy(sizePolicy)
        self.Content.setStyleSheet("")
        self.Content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Content.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Content.setLineWidth(0)
        self.Content.setObjectName("Content")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Content)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(parent=self.Content)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(8, 10, 8, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_9.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap(":/icon/search.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_9.setIcon(icon8)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 16))
        self.pushButton_9.setDefault(False)
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_2)
        self.stackedWidget.setStyleSheet("border: None")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Main_page = QtWidgets.QWidget()
        self.Main_page.setObjectName("Main_page")
        self.main_title = QtWidgets.QLabel(parent=self.Main_page)
        self.main_title.setGeometry(QtCore.QRect(5, 160, 841, 151))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.main_title.setFont(font)
        self.main_title.setStyleSheet("color: rgb(166, 166, 166);")
        self.main_title.setObjectName("main_title")
        self.stackedWidget.addWidget(self.Main_page)
        self.Playlist_page = QtWidgets.QWidget()
        self.Playlist_page.setObjectName("Playlist_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Playlist_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playlist_table = PlayerListWidget(parent=self.Playlist_page)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(11)
        self.playlist_table.setFont(font)
        self.playlist_table.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff
        )
        self.playlist_table.setAlternatingRowColors(False)
        self.playlist_table.setIconSize(QtCore.QSize(50, 50))
        self.playlist_table.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.playlist_table.setObjectName("playlist_table")
        self.verticalLayout.addWidget(self.playlist_table)
        self.stackedWidget.addWidget(self.Playlist_page)
        self.Track_page = QtWidgets.QWidget()
        self.Track_page.setObjectName("Track_page")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.Track_page)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.tracks_table = PlayerTableWidget(parent=self.Track_page)
        self.tracks_table.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff
        )
        self.tracks_table.setAlternatingRowColors(False)
        self.tracks_table.setShowGrid(True)
        self.tracks_table.setObjectName("tracks_table")
        self.tracks_table.setColumnCount(3)
        self.tracks_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tracks_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tracks_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tracks_table.setHorizontalHeaderItem(2, item)
        self.tracks_table.horizontalHeader().setVisible(False)
        self.tracks_table.horizontalHeader().setCascadingSectionResizes(False)
        self.tracks_table.horizontalHeader().setDefaultSectionSize(180)
        self.tracks_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout1.addWidget(self.tracks_table)
        self.stackedWidget.addWidget(self.Track_page)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.dropdown_menu = QtWidgets.QFrame(parent=self.centralwidget)
        self.dropdown_menu.setGeometry(QtCore.QRect(615, 505, 361, 42))
        self.dropdown_menu.setStyleSheet(
            "background-color: rgb(68, 68, 68);\n" "border: none;"
        )
        self.dropdown_menu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dropdown_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dropdown_menu.setLineWidth(0)
        self.dropdown_menu.setObjectName("dropdown_menu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dropdown_menu)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.volume_slider = QtWidgets.QSlider(parent=self.dropdown_menu)
        self.volume_slider.setEnabled(True)
        self.volume_slider.setStyleSheet(
            "QSlider::groove:horizontal {\n"
            "    height: 5px;\n"
            "    margin: 0px;\n"
            "    border-radius: 3px;\n"
            "    background: #B0AEB1;\n"
            "    background: rgb(255, 255, 255, 0.4);\n"
            "}\n"
            "\n"
            "QSlider::handle:horizontal {\n"
            "    background: #fff;\n"
            "    width: 5px;\n"
            "    margin: -3px 0;\n"
            "}\n"
            "\n"
            "QSlider::sub-page:qlineargradient {\n"
            "    background: #ffdb4d;\n"
            "    border-radius: 3px;\n"
            "}\n"
            ""
        )
        self.volume_slider.setProperty("value", 50)
        self.volume_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.verticalLayout_6.addWidget(self.volume_slider)
        self.frame_3.raise_()
        self.Content.raise_()
        self.sidebar.raise_()
        self.dropdown_menu.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1011, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(parent=self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.logout_action = QtGui.QAction(parent=MainWindow)
        self.logout_action.setObjectName("logout_action")
        self.about_action = QtGui.QAction(parent=MainWindow)
        self.about_action.setObjectName("about_action")
        self.menu.addAction(self.logout_action)
        self.menu_2.addAction(self.about_action)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Яндекс Музыка"))
        self.my_likes.setText(_translate("MainWindow", "Мне нравится"))
        self.my_wave.setText(_translate("MainWindow", "Моя волна"))
        self.my_playlist.setText(_translate("MainWindow", "Плейлисты"))
        self.my_albums.setText(_translate("MainWindow", "Альбомы"))
        self.my_queue.setText(_translate("MainWindow", "Очередь"))
        self.like_button.setShortcut(
            _translate("MainWindow", "Media Previous, Media Previous")
        )
        self.current_time.setText(_translate("MainWindow", "0:00"))
        self.wait_time.setText(_translate("MainWindow", "0:00"))
        self.previus_button.setShortcut(
            _translate("MainWindow", "Media Previous, Media Previous")
        )
        self.playpause_button.setShortcut(_translate("MainWindow", "Space"))
        self.forward_button.setShortcut(
            _translate("MainWindow", "Media Next, Media Next")
        )
        self.main_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Выберите что-то слева</p></body></html>',
            )
        )
        item = self.tracks_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tracks_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Исполнитель"))
        item = self.tracks_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Альбом"))
        self.menu.setTitle(_translate("MainWindow", "Аккаунт"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.logout_action.setText(_translate("MainWindow", "Выйти из аккаунта"))
        self.about_action.setText(_translate("MainWindow", "О программе"))


from yandex_music_qt_app.widgets.PlayerList import PlayerListWidget, PlayerTableWidget
